#!/bin/bash
{
	#////////////////////////////////////
	# SourceForge 2.0 Survey Script
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@sf2.com / sf2.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Allows to send SourceForge 2.0 usage info via SFTP to SourceForge 2.0 server
	# - Includes hardware info, SourceForge 2.0 version+branch, installed software, benchmark results and some setup info
	# - No private data is sent, no one can identify you.
	# - Runs after every sf2-update and sf2-software install, if user opted in
	# - Summary can be visited at: https://sf2.com/survey/
	# - Allows the SourceForge 2.0 project to focus development based on popularity
	# - Further info: https://sf2.com/docs/sf2_tools/#sf2-survey
	#
	# Usage:
	# - /usr/lib/sf2/sf2-survey		Interactive menu to opt in or out
	# - /usr/lib/sf2/sf2-survey 1	Non-interactively send survey data or empty file, based on previous user choice
	#
	# File sent format: $G_HW_UUID.txt
	#////////////////////////////////////

	# Import SourceForge 2.0-Globals --------------------------------------------------------------
	. /usr/lib/sf2/func/sf2-globals
	readonly G_PROGRAM_NAME='SourceForge 2.0-Survey'
	G_CHECK_ROOT_USER "$@"
	G_INIT
	# Import SourceForge 2.0-Globals --------------------------------------------------------------

	# Grab input
	[[ $1 == 1 ]] && INPUT=1 || INPUT=0

	readonly FP_UPLOAD="$G_HW_UUID.txt"
	readonly SFTP_ADDR='ssh.sf2.com:29248'
	readonly SFTP_USER='sf2-survey'
	readonly SFTP_PASS='upload2sf2'

	Generate_File(){

		# SourceForge 2.0 version
		local version="$G_DIETPI_VERSION_CORE.$G_DIETPI_VERSION_SUB"

		# Current Git owner/branch
		local gitbranch="$G_GITOWNER/$G_GITBRANCH"

		# Active network interface
		local network_interface=$(G_GET_NET -q iface)
		[[ $network_interface ]] || network_interface='NONE'

		# Autostart index
		local autostart_index
		[[ -f '/usr/lib/sf2/.sf2-autostart_index' ]] && read -r autostart_index < /usr/lib/sf2/.sf2-autostart_index
		[[ $autostart_index ]] || autostart_index=0

		# rootfs on SD card/eMMC?
		local mmc=0
		[[ $G_ROOTFS_DEV == '/dev/mmcblk'* ]] && mmc=1

		cat << _EOF_ > "$FP_UPLOAD"
((aDIETPI_VERSION[$version]++))
((aGIT_BRANCH[$gitbranch]++))
((aDEVICE_NAME[$G_HW_MODEL_NAME]++))
((aCPU_ARCH[$G_HW_ARCH_NAME]++))
((aCPU_COUNT[$G_HW_CPU_CORES]++))
((aDISTRO_VERSION[$G_DISTRO_NAME]++))
((aAUTOSTART_OPTION[\${aAUTOSTART_NAME[$autostart_index]:=$autostart_index}]++))
((aAUTO_SETUP_AUTOMATED[$(grep -cm1 '^[[:blank:]]*AUTO_SETUP_AUTOMATED=1' /etc/sf2/config.txt)]++))
((aNETWORK_INTERFACE[$network_interface]++))
MMC=$mmc
_EOF_

		# RPi: Raspbian/Raspberry Pi OS (32-bit) or Debian/Raspberry Pi OS (64-bit)?
		(( $G_HW_MODEL < 10 )) && echo "((aRASPBIAN[$G_RASPBIAN]++))" >> "$FP_UPLOAD"

		# SourceForge 2.0-Software installs
		[[ -f '/usr/lib/sf2/.installed' ]] && while read -r software
		do
			software=${software##*[}
			software=${software%%]*}
			disable_error=1 G_CHECK_VALIDINT "$software" && echo "((aSOFTWARE[\${aSOFTWARE_NAME${G_DIETPI_VERSION_CORE}_${G_DIETPI_VERSION_SUB}[$software]:=$software}]++))" >> "$FP_UPLOAD"

		done < <(grep ']=2$' /usr/lib/sf2/.installed)

		# SourceForge 2.0-Benchmark results
		[[ -f '/var/lib/sf2/sf2-benchmark/results' ]] && cat /var/lib/sf2/sf2-benchmark/results >> "$FP_UPLOAD"

	}

	Send_File(){

		# Validate file name
		[[ $FP_UPLOAD =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.txt$ ]] || { G_DIETPI-NOTIFY 1 "Skipping sending/purging survey data as the survey UUID \"${FP_UPLOAD%.txt}\" is invalid..."; return 1; }

		# Check if our ssh.sf2.com SSH host key is present
		if [[ ! -f '/root/.ssh/known_hosts' ]] || ! grep -Eq '^\[?ssh.sf2.com(]:29248)?[[:blank:]]' /root/.ssh/known_hosts
		then
			# If missing, offer to re-add it
			if G_WHIP_YESNO '[WARNING] ssh.sf2.com SSH host key is missing\n\nOur ssh.sf2.com SSH host key, required to send or purge survey data and bug reports, is missing in /root/.ssh/known_hosts. Shall we re-create it to proceed with sending/purging the bug report?'
			then
				[[ -d '/root/.ssh' ]] || G_EXEC mkdir /root/.ssh
				[[ -f '/root/.ssh/known_hosts' ]] || > /root/.ssh/known_hosts
				if (( $G_DISTRO < 7 ))
				then
					G_CONFIG_INJECT '\[?ssh.sf2.com(]:29248)?[[:blank:]]' '[ssh.sf2.com]:29248 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDE6aw3r6aOEqendNu376iiCHr9tGBIWPgfrLkzjXjEsHGyVSUFNnZt6pftrDeK7UX+qX4FxOwQlugG4fymOHbimRCFiv6cf7VpYg1Ednquq9TLb7/cIIbX8a6AuRmX4fjdGuqwmBq3OG7ZksFcYEFKt5U4mAJIaL8hXiM2iXjgY02LqiQY/QWATsHI4ie9ZOnwrQE+Rr6mASN1BVFuIgyHIbwX54jsFSnZ/7CdBMkuAd9B8JkxppWVYpYIFHE9oWNfjh/epdK8yv9Oo6r0w5Rb+4qaAc5g+RAaknHeV6Gp75d2lxBdCm5XknKKbGma2+/DfoE8WZTSgzXrYcRlStYN' /root/.ssh/known_hosts
				else
					G_CONFIG_INJECT '\[?ssh.sf2.com(]:29248)?[[:blank:]]' '[ssh.sf2.com]:29248 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJdEPlagpQ+RVHNOX3jkG1Bya7Oza1dAke8h8NszVW84' /root/.ssh/known_hosts
				fi
			else
				G_DIETPI-NOTIFY 1 'Skipping sending/purging survey data as our ssh.sf2.com SSH host key is missing in /root/.ssh/known_hosts...'
				return 1
			fi
		fi

		if (( $OPTED_IN ))
		then
			[[ -f $FP_UPLOAD ]] || Generate_File
		else
			# Send empty file to overwrite existing data, "rm" is not possible due to missing file list permissions
			> "$FP_UPLOAD"
		fi

		# Upload to server
		local timeout=$(sed -n '/^[[:blank:]]*CONFIG_G_CHECK_URL_TIMEOUT=/{s/^[^=]*=//p;q}' /etc/sf2/config.txt) G_EXEC_DESC='Sending survey data'
		(( $OPTED_IN )) || G_EXEC_DESC='Purging survey data'
		# - Timeout x2 for DNS resolving + connection, upload itself is done in no time
		G_EXEC_NOHALT=1 G_EXEC curl -m $(( ${timeout:-5} * 2 )) -sT "$FP_UPLOAD" "sftp://$SFTP_USER:$SFTP_PASS@$SFTP_ADDR/survey/"
		return $?

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	# Read opt in/out choice: 1=yes and send data | 0=no and purge data
	OPTED_IN=$(sed -n '/^[[:blank:]]*SURVEY_OPTED_IN=[01]$/{s/^[^=]*=//p;q}' /etc/sf2/config.txt)
	# - No (valid) choice done yet
	if [[ $OPTED_IN != [01] ]]
	then
		# Do not send data without user interactively opted in!
		OPTED_IN=0
		# Ask for choice, if interactive
		(( $G_INTERACTIVE )) && INPUT=0
	fi

	# Interactive menu
	until (( $INPUT ))
	do
		G_WHIP_MENU_ARRAY=(

			'Show' ': Show me the upload file content'
			'1' ': Opt IN and upload data'
			'0' ': Opt OUT and purge uploaded data'
		)

		G_WHIP_DEFAULT_ITEM=$OPTED_IN
		if G_WHIP_MENU 'SourceForge 2.0-Survey would like to collect anonymous usage statistics.
This allows us to focus development based on popularity.
 - NO private data will be collected and NO ONE can identify you based on it.
 - The data is sent via secured SFTP connection, stored unreadable to the public upload user.
 - If you agree, your uploaded data will be updated after each SourceForge 2.0-Update and SourceForge 2.0-Software install.
 - Current survey statistics can be reviewed at: https://sf2.com/survey/
\nWould you like to join SourceForge 2.0-Survey?'
		then
			if [[ $G_WHIP_RETURNED_VALUE == 'Show' ]]
			then
				Generate_File
				G_WHIP_VIEWFILE "$FP_UPLOAD"
				continue # Stay in loop
			else
				OPTED_IN=$G_WHIP_RETURNED_VALUE
				G_CONFIG_INJECT 'SURVEY_OPTED_IN=' "SURVEY_OPTED_IN=$OPTED_IN" /etc/sf2/config.txt
			fi
		fi

		break
	done

	# Send data if opted in or empty file if opted out
	Send_File

	#-----------------------------------------------------------------------------------
	exit $?
	#-----------------------------------------------------------------------------------
}
