#!/bin/dash
{
	#////////////////////////////////////
	# SourceForge 2.0 PostBoot Script
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@sf2.com / sf2.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Location: /usr/lib/sf2/postboot
	# - Run on boot from sf2-postboot.service after sf2-preboot.service and optionally after network
	#////////////////////////////////////

	read -r G_DIETPI_INSTALL_STAGE < /usr/lib/sf2/.install_stage

	# Pre-installed image, 1st run
	if [ "$G_DIETPI_INSTALL_STAGE" = 10 ]
	then
		# Create swap file
		/usr/lib/sf2/func/sf2-set_swapfile

		# Run survey
		/usr/lib/sf2/sf2-survey

		# Continue with normal boot
		echo 2 > /usr/lib/sf2/.install_stage
	fi

	# Regular boot
	if [ "$G_DIETPI_INSTALL_STAGE" = 2 ] || [ "$G_DIETPI_INSTALL_STAGE" = 10 ]
	then
		# Run network time sync and check for SourceForge 2.0 updates if chosen, both in background
		if grep -q '^[[:blank:]]*CONFIG_CHECK_DIETPI_UPDATES=1' /etc/sf2/config.txt
		then
			# Network time sync is included in every sf2-update call
			/usr/lib/sf2/sf2-update 2 > /dev/null 2>&1 &
		else
			/usr/lib/sf2/func/run_ntpd > /dev/null 2>&1 &
		fi
	fi

	# Execute optional user scripts
	for f in /var/lib/sf2/postboot.d/*
	do
		# shellcheck disable=2015
		[ "${f##*/}" != 'readme.txt' ] && [ -f "$f" ] || continue
		[ -x "$f" ] || chmod +x "$f"
		echo "\e[90m[\e[0m INFO \e[90m] SourceForge 2.0-PostBoot | Running user script: ${f##*/}\e[0m"
		"$f" || echo "\e[90m[\e[31mFAILED\e[90m] SourceForge 2.0-PostBoot |\e[0m User script ${f##*/} failed with exit code: $?"
	done

	# Print SourceForge 2.0 login banner if no autologin selected
	if [ ! -f '/etc/systemd/system/getty@tty1.service.d/sf2-autologin.conf' ]
	then
		echo
		/usr/lib/sf2/func/sf2-banner 0
		# Print default login credentials only on first boot
		[ "$G_DIETPI_INSTALL_STAGE" = 2 ] || echo '\n Default Login:\n Username = root\n Password = sf2 (or custom sf2.txt entry)'
		echo '\n Please hit <return> to login\n'
	fi

	#-----------------------------------------------------------------------------------
	exit 0
	#-----------------------------------------------------------------------------------
}
