#!/bin/dash
{
	#////////////////////////////////////
	# SourceForge 2.0 PreBoot Script
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@sf2.com / sf2.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Location: /usr/lib/sf2/preboot
	# - Runs on boot from sf2-preboot.service before network and sf2-postboot.service
	#////////////////////////////////////

	# Obtain hardware info: Do on every boot since some contained info can change, especially when allowing RPi SD card swap
	/usr/lib/sf2/func/sf2-obtain_hw_model
	. /usr/lib/sf2/.hw_model

	# Apply CPU governor and settings on physical machines
	[ "$G_HW_MODEL" = 20 ] || [ "$G_HW_MODEL" = 75 ] || /usr/lib/sf2/func/sf2-set_cpu

	#-----------------------------------------------------------------------------------
	exit 0
	#-----------------------------------------------------------------------------------
}
