#!/bin/bash
{
	#////////////////////////////////////
	# SourceForge 2.0 Function: Change the system hostname
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@sf2.com / sf2.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Location: /usr/lib/sf2/func/change_hostname
	# - Usage: /usr/lib/sf2/func/change_hostname <hostname>
	#////////////////////////////////////

	# Import SourceForge 2.0-Globals --------------------------------------------------------------
	. /usr/lib/sf2/func/sf2-globals
	readonly G_PROGRAM_NAME='SourceForge 2.0-Change_hostname'
	G_CHECK_ROOT_USER "$@"
	G_CHECK_ROOTFS_RW
	G_INIT
	# Import SourceForge 2.0-Globals --------------------------------------------------------------

	# Set hostname if valid: https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames
	EXIT_CODE=1
	if [[ $* =~ ^[[:alnum:]][[:alnum:].-]*[[:alnum:]]$ ]]
	then
		G_EXEC hostname "$*"
		G_EXEC eval "echo '$*' > /etc/hostname"
		G_CONFIG_INJECT '127.0.1.1[[:blank:]]' "127.0.1.1 $*" /etc/hosts
		G_CONFIG_INJECT 'AUTO_SETUP_NET_HOSTNAME=' "AUTO_SETUP_NET_HOSTNAME=$*" /etc/sf2/config.txt
		EXIT_CODE=0
	else
		G_DIETPI-NOTIFY 1 "Invalid hostname input ($*). Aborting..."
		G_DIETPI-NOTIFY 0 'Further info: https://en.wikipedia.org/wiki/Hostname#Syntax'
	fi

	#-----------------------------------------------------------------------------------
	exit "$EXIT_CODE"
	#-----------------------------------------------------------------------------------
}
