#!/bin/bash
{
	#////////////////////////////////////
	# SourceForge 2.0 Function:
	# - Creates a MariaDB database
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@sf2.com / sf2.com
	#////////////////////////////////////
	# Usage:
	# - /usr/lib/sf2/func/create_mysql_db <DATABASE_NAME> <DATABASE_USER> <DATABASE_PW>
	#
	# Drop database:
	# - mysqladmin -f drop <DATABASE_NAME>
	#////////////////////////////////////

	# Import SourceForge 2.0-Globals --------------------------------------------------------------
	. /usr/lib/sf2/func/sf2-globals
	readonly G_PROGRAM_NAME='SourceForge 2.0-Create_MySQL_DB'
	G_CHECK_ROOT_USER "$@"
	G_INIT
	# Import SourceForge 2.0-Globals --------------------------------------------------------------

	# Grab input
	readonly DATABASE_NAME=$1 DATABASE_USER=$2 DATABASE_PW=$3

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////

	# Skip database creation if already existent
	[[ -d '/var/lib/mysql/'$DATABASE_NAME ]] && { G_DIETPI-NOTIFY 2 "MariaDB database $DATABASE_NAME already exists. Aborting..."; exit 0; }

	readonly MESSAGE="Creating MariaDB database $DATABASE_NAME for user $DATABASE_USER"
	G_DIETPI-NOTIFY 2 "$MESSAGE"

	G_EXEC systemctl start mariadb

	# Generate DB
	# - 'identified by' overwrites unix_socket authentication, thus use this for non-root users only.
	# - Database names can only be quoted via backticks, passwords only via single quotes.
	grant_privileges="grant all privileges on \`$DATABASE_NAME\`.* to '$DATABASE_USER'@localhost identified by '$DATABASE_PW';flush privileges"
	[[ $DATABASE_USER != 'root' ]] || grant_privileges=
	mysql -e "create database \`$DATABASE_NAME\`;$grant_privileges"
	exit_code=$?

	#-------------------------------------------------------------------------------------
	G_DIETPI-NOTIFY -1 "$exit_code" "$MESSAGE"
	exit "$exit_code"
	#-------------------------------------------------------------------------------------
}
